apiVersion: apps/v1
kind: Deployment
metadata: 
   name: currency-converter-client
spec:
   replicas: 1
   selector:
     matchLabels:
        app: currency-converter-client
   template:
      metadata: 
        name: currency-converter-client
        labels:
           app: currency-converter-client
      spec:
        containers: 
           - name: currency-converter-client
             image: amitfegade121/currency-converter-client
             ports:
                - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
   name: currency-converter-client
spec:
   selector:
      app: currency-converter-client
   type: NodePort
   ports:
     - name: "80"
       port: 80
       targetPort: 80
       nodePort: 30000
