apiVersion: apps/v1
kind: Deployment
metadata:
   name: currency-conversion-service
spec:
   replicas: 1
   selector:
      matchLabels: 
          app: currency-conversion-service
   template:
      metadata: 
         name: currency-conversion-service
         labels: 
            app: currency-conversion-service
      spec:
          containers:
              - name: currency-conversion-service
                image: amitfegade121/currency-conversion-service:1.0
                ports:
                   - containerPort: 8081            

---

apiVersion: v1
kind: Service
metadata:
   name: currency-conversion-service
spec:
   selector: 
       app: currency-conversion-service
   type: NodePort    
   ports: 
      - name: "8081"
        port: 8081
        targetPort: 8081
        nodePort: 30001   
         
         
         