apiVersion: apps/v1
kind: Deployment
metadata:
   name: currency-exchange-service
spec:
   replicas: 1
   selector:
      matchLabels:
         app: currency-exchange-service
   template:
      metadata:
         name: currency-exchange-service
         labels: 
            app: currency-exchange-service
      spec: 
          containers: 
             - name: currency-exchange-service
               image: amitfegade121/currency-exchange-service:1.0
               ports:
                  - containerPort: 8082
               env:
                  - name: MONGO_USERNAME
                    valueFrom:
                       secretKeyRef:
                          name: mongodb-secret 
                          key: username
                  - name: MONGO_PASSWORD
                    valueFrom:
                       secretKeyRef:
                          name: mongodb-secret
                          key: password                 

---

apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
spec:
  selector: 
    app: currency-exchange-service
  type: NodePort
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
      nodePort: 30002   

     
     
     
     
     
     
     
