apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongodb   
spec:
   replicas: 1
   selector:
      matchLabels:
          service: mongodb
   template:
      metadata:
         name: mongodb
         labels:
            service: mongodb
      spec:
         containers: 
            - name: mongodb
              image: mongo:latest
              ports:
                - containerPort: 27017
              env:
                - name: MONGO_INITDB_ROOT_USERNAME
                  valueFrom: 
                     secretKeyRef:
                        key: username
                        name: mongodb-secret      
                - name: MONGO_INITDB_ROOT_PASSWORD
                  valueFrom:
                     secretKeyRef:
                         key: password
                         name: mongodb-secret
              volumeMounts: 
                 - name: mongodb-volume
                   mountPath: /data/db                                  
         volumes:
             - name: mongodb-volume
               persistentVolumeClaim:
                   claimName: mongodb-volume     
---

apiVersion: v1
kind: Service
metadata:
   name: mongodb-service   
spec:  
   selector:
      service: mongodb
   ports:
     - name: "27017"
       port: 27017
       targetPort: 27017   
